vim.cmd("language en_US")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set mouse=a")
vim.cmd("set autoindent")
vim.cmd("set tabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set smarttab")
vim.cmd("set softtabstop=4")

vim.keymap.set('n', '<C-c>', '"+y', { noremap = true})
vim.keymap.set('v', '<C-c>', '"+y', { noremap = true})
vim.keymap.set('i', '<C-c>', '<Esc>"+y`a', { noremap = true})
vim.keymap.set('n', '<C-v>', '"+p', { noremap = true})
vim.keymap.set('v', '<C-v>', '"+p', { noremap = true})
vim.keymap.set('i', '<C-v>', '<Esc>"+p`a', { noremap = true})
vim.keymap.set('n', '<C-z>', ':undo<CR>', { noremap = true})
vim.keymap.set('v', '<C-z>', ':undo<CR>', { noremap = true})
vim.keymap.set('i', '<C-z>', '<Esc>:undo<CR>i', { noremap = true})
